require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const cloudinary = require('cloudinary').v2;
const fs = require('fs');
const path = require('path');

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
});

const artifactDir = 'C:\\Users\\impra\\.gemini\\antigravity-ide\\brain\\84d2bb83-3363-49ff-855e-5b5716127657';

const avatars = [
  'avatar_1_1784873900188.png',
  'avatar_2_1784873911193.png',
  'avatar_3_1784873921830.png',
  'avatar_5_1784873957922.png',
  'avatar_6_1784873941034.png'
];

const banners = [
  'banner_1_1784873966634.png',
  'banner_2_1784873983455.png',
  'banner_3_1784873994391.png',
  'banner_4_1784874004544.png',
  'banner_5_1784874021946.png'
];

async function uploadFile(filePath, folder) {
  try {
    const result = await cloudinary.uploader.upload(filePath, { folder });
    console.log(`Uploaded to ${folder}: ${result.secure_url}`);
    return result.secure_url;
  } catch (err) {
    console.error('Error uploading', filePath, err);
    throw err;
  }
}

async function main() {
  const defaultAvatars = [];
  const defaultBanners = [];

  console.log('Uploading Avatars...');
  for (const avatar of avatars) {
    const filePath = path.join(artifactDir, avatar);
    const url = await uploadFile(filePath, 'default_avatars');
    defaultAvatars.push(url);
  }

  console.log('Uploading Banners...');
  for (const banner of banners) {
    const filePath = path.join(artifactDir, banner);
    const url = await uploadFile(filePath, 'default_banners');
    defaultBanners.push(url);
  }

  const configContent = `// Automatically generated by upload script\nmodule.exports = {\n  DEFAULT_AVATARS: ${JSON.stringify(defaultAvatars, null, 2)},\n  DEFAULT_BANNERS: ${JSON.stringify(defaultBanners, null, 2)}\n};\n`;

  const configPath = path.join(__dirname, '../src/config/defaultAssets.js');
  fs.writeFileSync(configPath, configContent);
  console.log('Successfully generated defaultAssets.js at', configPath);
}

main().catch(console.error);
