// Automatically generated by upload script
const cloudName = process.env.CLOUDINARY_CLOUD_NAME || "mne6vzev";

module.exports = {
  DEFAULT_AVATARS: [
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830837/default_avatars/dwwq0hfr4uickyfa8pan.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830838/default_avatars/jjjy4sldwahnvov6lsyh.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830839/default_avatars/k4kf7gpgw313cyjjzwkh.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830840/default_avatars/co54jfqkhgu7ajwmcjaj.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830841/default_avatars/e6v4iechcnvhigsczkyy.jpg`
  ],
  DEFAULT_BANNERS: [
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830841/default_banners/getor4hyq0u5gbeinzij.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830842/default_banners/gpo42rcudkhlsqbrsj08.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830843/default_banners/x1jprcaoeb2f0knkj0nz.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830844/default_banners/grkveda1mrys7zh4a0ij.jpg`,
    `https://res.cloudinary.com/${cloudName}/image/upload/v1785830845/default_banners/tamogk47hpxhjwbcqm9c.jpg`
  ]
};

