// Automatically generated by upload script
module.exports = {
  DEFAULT_AVATARS: [
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874184/default_avatars/pwymnq2xkryqax7x82oe.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874185/default_avatars/bma6efythq59wsqzmt0k.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874186/default_avatars/spgzhdh1fexvjx9cbyw8.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874188/default_avatars/b3vw3idr9n3yyooz7yje.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874189/default_avatars/mqxxzebk0eddp7dryitd.jpg"
],
  DEFAULT_BANNERS: [
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874190/default_banners/ozoky2h5lbx0wwbrgrsx.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874192/default_banners/dmrd6lmgdkgcbbwmsfiw.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874193/default_banners/rcz6wok7tvsd6i67hmmk.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874194/default_banners/dhmpkxahuuttbyegzj7c.jpg",
  "https://res.cloudinary.com/yawspwks/image/upload/v1784874195/default_banners/v6e8lk9paqzo7mxqweo2.jpg"
]
};
